# Documentation:
# https://checkmarx.atlassian.net/wiki/spaces/Checkmarx One/pages/6147408761/CI+CD+with+CxSCA+Resolver
#

name: SCA Resolver Example

on:
  push:
    branches:
      [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Download SCA Resolver
        run: |
          wget https://sca-downloads.s3.amazonaws.com/cli/latest/ScaResolver-linux64.tar.gz
          tar -xzvf ScaResolver-linux64.tar.gz
          rm -rf ScaResolver-linux64.tar.gz

      - name: Run Checkmarx One CLI Scan
        run: |
            project_name: ${{ github.repository }} 
            branch: ${GITHUB_REF##*/} 
            base_uri: ${{ secrets.CX_BASE_URI }} 
            cx_tenant: cdac
            cx_client_id: ${{ secrets.CX_CLIENT_ID }} 
            cx_client-secret: ${{ secrets.CX_CLIENT_SECRET }} 
            cx_tenant: cdac
            cx --sca-resolver --help
            --sca-resolver ./ScaResolver
